repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
        - id: black
          args: [--line-length=100]
          types: [python]

  - repo: https://github.com/pycqa/flake8.git
    rev: 7.0.0
    hooks:
        - id: flake8
          additional_dependencies: [flake8-print]
          args: [--max-line-length=100]
          types: [python]
